/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'familias-tratamiento': FamiliasTratamiento;
    tratamientos: Tratamiento;
    testimonios: Testimonio;
    galeria: Galeria;
    'instagram-posts': InstagramPost;
    'paginas-legales': PaginasLegale;
    'verificacion-contenido': VerificacionContenido;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'familias-tratamiento': FamiliasTratamientoSelect<false> | FamiliasTratamientoSelect<true>;
    tratamientos: TratamientosSelect<false> | TratamientosSelect<true>;
    testimonios: TestimoniosSelect<false> | TestimoniosSelect<true>;
    galeria: GaleriaSelect<false> | GaleriaSelect<true>;
    'instagram-posts': InstagramPostsSelect<false> | InstagramPostsSelect<true>;
    'paginas-legales': PaginasLegalesSelect<false> | PaginasLegalesSelect<true>;
    'verificacion-contenido': VerificacionContenidoSelect<false> | VerificacionContenidoSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('es' | 'ca' | 'en' | 'it' | 'fr' | 'pt')
    | ('es' | 'ca' | 'en' | 'it' | 'fr' | 'pt')[];
  globals: {
    'ajustes-globales': AjustesGlobale;
    'contenido-inicio': ContenidoInicio;
    'contenido-sobre-gapssa': ContenidoSobreGapssa;
  };
  globalsSelect: {
    'ajustes-globales': AjustesGlobalesSelect<false> | AjustesGlobalesSelect<true>;
    'contenido-inicio': ContenidoInicioSelect<false> | ContenidoInicioSelect<true>;
    'contenido-sobre-gapssa': ContenidoSobreGapssaSelect<false> | ContenidoSobreGapssaSelect<true>;
  };
  locale: 'es' | 'ca' | 'en' | 'it' | 'fr' | 'pt';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * admin: gestiona usuarios y configuración. editor: gestiona contenido.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Texto alternativo significativo. Para imágenes puramente decorativas, usa una descripción vacía únicamente cuando el componente que la use la trate explícitamente como decorativa (alt="").
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "familias-tratamiento".
 */
export interface FamiliasTratamiento {
  id: number;
  /**
   * Identificador estable, igual en los 6 idiomas (ej. "masajes").
   */
  slug: string;
  titulo: string;
  descripcion?: string | null;
  imagen?: (number | null) | Media;
  orden: number;
  visible: boolean;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tratamientos".
 */
export interface Tratamiento {
  id: number;
  /**
   * Reservado para la futura vinculación con CTratamiento en EspoCRM (Fase 4+). No usado todavía.
   */
  externalEspocrmId?: string | null;
  /**
   * Identificador estable, igual en los 6 idiomas.
   */
  slug: string;
  familia: number | FamiliasTratamiento;
  titulo: string;
  descripcion?: string | null;
  beneficios?:
    | {
        texto?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Requisitos previos o contraindicaciones GENERALES (nunca afirmaciones clínicas ni contraindicaciones médicas específicas — PROJECT_CONTEXT.md §6).
   */
  requisitosContraindicaciones?: string | null;
  preguntasFrecuentes?:
    | {
        pregunta?: string | null;
        respuesta?: string | null;
        id?: string | null;
      }[]
    | null;
  imagenes?: (number | Media)[] | null;
  /**
   * Nunca un importe: FacturaScripts es la futura fuente de verdad del precio (PROJECT_CONTEXT.md §11).
   */
  indicadorPrecio: 'consultar' | 'pendiente' | 'oculto';
  /**
   * Además de publicar el documento, debe marcarse visible para aparecer en el catálogo público.
   */
  visible: boolean;
  destacado: boolean;
  orden: number;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios".
 */
export interface Testimonio {
  id: number;
  texto: string;
  /**
   * Solo nombre e inicial del apellido (ej. "María G."). Nunca el apellido completo.
   */
  autor: string;
  visible: boolean;
  orden: number;
  /**
   * Indicador interno de que existe autorización de uso promocional. No es el documento en sí.
   */
  autorizacionRegistrada: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria".
 */
export interface Galeria {
  id: number;
  imagen: number | Media;
  alt: string;
  categoria?: string | null;
  orden: number;
  visible: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts".
 */
export interface InstagramPost {
  id: number;
  imagen: number | Media;
  texto?: string | null;
  url: string;
  fecha?: string | null;
  orden: number;
  visible: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas-legales".
 */
export interface PaginasLegale {
  id: number;
  tipo: 'aviso-legal' | 'privacidad' | 'cookies' | 'condiciones-reserva';
  titulo: string;
  contenido: string;
  version: string;
  fecha: string;
  estado: 'provisional' | 'validado';
  /**
   * Se recomienda mantener activo mientras el estado sea "provisional".
   */
  seoNoIndex: boolean;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Verificación técnica de Fase 1 (persistencia, localización, control de acceso) — no es catálogo real.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verificacion-contenido".
 */
export interface VerificacionContenido {
  id: number;
  titulo: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'familias-tratamiento';
        value: number | FamiliasTratamiento;
      } | null)
    | ({
        relationTo: 'tratamientos';
        value: number | Tratamiento;
      } | null)
    | ({
        relationTo: 'testimonios';
        value: number | Testimonio;
      } | null)
    | ({
        relationTo: 'galeria';
        value: number | Galeria;
      } | null)
    | ({
        relationTo: 'instagram-posts';
        value: number | InstagramPost;
      } | null)
    | ({
        relationTo: 'paginas-legales';
        value: number | PaginasLegale;
      } | null)
    | ({
        relationTo: 'verificacion-contenido';
        value: number | VerificacionContenido;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "familias-tratamiento_select".
 */
export interface FamiliasTratamientoSelect<T extends boolean = true> {
  slug?: T;
  titulo?: T;
  descripcion?: T;
  imagen?: T;
  orden?: T;
  visible?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tratamientos_select".
 */
export interface TratamientosSelect<T extends boolean = true> {
  externalEspocrmId?: T;
  slug?: T;
  familia?: T;
  titulo?: T;
  descripcion?: T;
  beneficios?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  requisitosContraindicaciones?: T;
  preguntasFrecuentes?:
    | T
    | {
        pregunta?: T;
        respuesta?: T;
        id?: T;
      };
  imagenes?: T;
  indicadorPrecio?: T;
  visible?: T;
  destacado?: T;
  orden?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonios_select".
 */
export interface TestimoniosSelect<T extends boolean = true> {
  texto?: T;
  autor?: T;
  visible?: T;
  orden?: T;
  autorizacionRegistrada?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galeria_select".
 */
export interface GaleriaSelect<T extends boolean = true> {
  imagen?: T;
  alt?: T;
  categoria?: T;
  orden?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-posts_select".
 */
export interface InstagramPostsSelect<T extends boolean = true> {
  imagen?: T;
  texto?: T;
  url?: T;
  fecha?: T;
  orden?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas-legales_select".
 */
export interface PaginasLegalesSelect<T extends boolean = true> {
  tipo?: T;
  titulo?: T;
  contenido?: T;
  version?: T;
  fecha?: T;
  estado?: T;
  seoNoIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verificacion-contenido_select".
 */
export interface VerificacionContenidoSelect<T extends boolean = true> {
  titulo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-globales".
 */
export interface AjustesGlobale {
  id: number;
  nombreComercial: string;
  logo?: (number | null) | Media;
  direccion?: {
    calle?: string | null;
    ciudad?: string | null;
    codigoPostal?: string | null;
    pais?: string | null;
  };
  horario?:
    | {
        dia: 'lunes' | 'martes' | 'miercoles' | 'jueves' | 'viernes' | 'sabado' | 'domingo';
        cerrado: boolean;
        /**
         * Ej. "09:00–21:00". Vacío si el día está cerrado.
         */
        franja?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Todos opcionales. La web los oculta mientras estén vacíos — no se rellenan hasta confirmarlos.
   */
  contacto?: {
    telefono?: string | null;
    whatsapp?: string | null;
    correoPublico?: string | null;
  };
  redesSociales?:
    | {
        plataforma: 'instagram' | 'facebook' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  ctaPrincipal?: {
    texto?: string | null;
    ruta?: ('reservar' | 'contacto') | null;
  };
  seoPorDefecto?: {
    titulo?: string | null;
    descripcion?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenido-inicio".
 */
export interface ContenidoInicio {
  id: number;
  /**
   * Admite varias líneas — se muestran tal cual en el titular del hero.
   */
  heroTitulo: string;
  heroSubtitulo?: string | null;
  heroImagen?: (number | null) | Media;
  introQuienSoy?: string | null;
  introFamilias?: string | null;
  introContacto?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenido-sobre-gapssa".
 */
export interface ContenidoSobreGapssa {
  id: number;
  bioTitulo?: string | null;
  bioTexto?: string | null;
  bioCita?: string | null;
  bioBullets?:
    | {
        texto: string;
        id?: string | null;
      }[]
    | null;
  bioImagen?: (number | null) | Media;
  proceso?:
    | {
        numero: number;
        titulo: string;
        descripcion: string;
        id?: string | null;
      }[]
    | null;
  diferenciadores?:
    | {
        iconoClave:
          | 'atencion-personalizada'
          | 'productos-premium'
          | 'experiencia-avalada'
          | 'cuidado-con-carino'
          | 'resultados-naturales'
          | 'seguimiento-individual';
        titulo: string;
        descripcion: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Vacío por defecto. Solo añadir cifras confirmadas por Gapssa, nunca estimaciones.
   */
  estadisticas?:
    | {
        valor: string;
        etiqueta: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ajustes-globales_select".
 */
export interface AjustesGlobalesSelect<T extends boolean = true> {
  nombreComercial?: T;
  logo?: T;
  direccion?:
    | T
    | {
        calle?: T;
        ciudad?: T;
        codigoPostal?: T;
        pais?: T;
      };
  horario?:
    | T
    | {
        dia?: T;
        cerrado?: T;
        franja?: T;
        id?: T;
      };
  contacto?:
    | T
    | {
        telefono?: T;
        whatsapp?: T;
        correoPublico?: T;
      };
  redesSociales?:
    | T
    | {
        plataforma?: T;
        url?: T;
        id?: T;
      };
  ctaPrincipal?:
    | T
    | {
        texto?: T;
        ruta?: T;
      };
  seoPorDefecto?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenido-inicio_select".
 */
export interface ContenidoInicioSelect<T extends boolean = true> {
  heroTitulo?: T;
  heroSubtitulo?: T;
  heroImagen?: T;
  introQuienSoy?: T;
  introFamilias?: T;
  introContacto?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenido-sobre-gapssa_select".
 */
export interface ContenidoSobreGapssaSelect<T extends boolean = true> {
  bioTitulo?: T;
  bioTexto?: T;
  bioCita?: T;
  bioBullets?:
    | T
    | {
        texto?: T;
        id?: T;
      };
  bioImagen?: T;
  proceso?:
    | T
    | {
        numero?: T;
        titulo?: T;
        descripcion?: T;
        id?: T;
      };
  diferenciadores?:
    | T
    | {
        iconoClave?: T;
        titulo?: T;
        descripcion?: T;
        id?: T;
      };
  estadisticas?:
    | T
    | {
        valor?: T;
        etiqueta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}